import Head from "next/head";
import PostsList from "@/pages/posts"; // パスを修正

import { PostType } from "@/types"; // 必要な場合、正しいパスに修正してください。

interface HomeProps {
  initialPosts: PostType[];
}

export default function Home({ initialPosts }: HomeProps) {
  return (
    <>
      <Head>
        <title>Next.js 12 with Tailwind and Zustand</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <PostsList initialPosts={initialPosts} />
      </div>
    </>
  );
}

export { getServerSideProps } from "@/pages/posts";
